### PR TITLE
More overrides

### PR DESCRIPTION
**Pull request by abejgonzalez**
This PR tries to add more overrides so that a DUT can closely match Dromajo

Changelist:
1. Load in a bootrom `*.img` file
2. Load in a `*.dts` file
3. Compact the space between the bootrom and the dts
4. Override the reset vector
5. Override the mmio_start/end from the command line

### CODE REVIEW

**Comment by abejgonzalez** [comment]
@jerryz123 Any comments before the PR to Dromajo? I need to clean this up a bit, but I want to ensure Linux boots first in co-simulation.

**Comment by jerryz123** [comment]
Wait I'm confused. Is the master branch of this fork supposed to be the version that works with BOOM? If so I recommend you rename it from master.

Also your changes seem like they should be PR'd into upstream Dromajo at some point

**Comment by abejgonzalez** [comment]
Sorry this is the branch that works with BOOM atm. I just have this as a PR so I can see the diff nicely.

**Comment by renau** [comment]
The loadable bootroom and patches look good even for mainline dromajo. We are trying to have a single dromajo shared across CPUs, it would be good if you can create a pull request.

**Comment by abejgonzalez** [comment]
Hi Jose, I'm planning on PR'ing to mainline when everything works with BOOM/Chipyard. I still have a couple of other things that I want to create overrides for.

**Pull request merged**
